name: Publish data workflow

on:
  push:
    branches: [main]
    paths:
      - 'img/**'
      - 'api/books.json'
      - 'api/npc-data.json'
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'
        path: 'main'

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'gh-pages'

    - name: Copy updated docs to gh-pages branch
      run: |
        mkdir gh-pages/img/library
        cp main/api/npc_data.json gh-pages/api/
        cp main/api/books.json gh-pages/api/
        cp main/img/npc/* gh-pages/img/npc/
        cp main/img/library/* gh-pages/img/library/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './gh-pages'
        publish_branch: gh-pages
        commit_message: "Deployed to GitHub Pages by GitHub Actions"
