name: NPC Workflow

on:
  pull_request:
    branches: [main]
    paths:
      - 'npc/**'
  push:
    branches: [main]
    paths:
      - 'api/conversations.json'
  workflow_dispatch:

jobs:
  validate:
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Validate changes
        run: |
          cd npc
          python ../src/validate.py

  convert:
    needs: validate
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Convert txt files to JSON
        run: |
          cd npc
          python ../src/txt_to_json.py
  
      - name: Commit conversations.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update conversations.json"
          file_pattern: api/conversations.json
          branch: ${{ github.head_ref }}

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'
        path: 'main'

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'gh-pages'

    - name: Copy updated docs to gh-pages branch
      run: |
        mkdir -p gh-pages/api
        cp main/api/conversations.json gh-pages/api/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './gh-pages'
        publish_branch: gh-pages
        commit_message: "Deployed to GitHub Pages by GitHub Actions"
        
