name: Deploy Docs changes

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'
        path: 'main'

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'tmp'

    - name: Copy updated docs to gh-pages branch
      run: |
        cp -r main/docs/* gh-pages/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './docs'
        publish_branch: gh-pages
        allow_empty_commit: true
        keep_files: true
        commit_message: "Deployed to GitHub Pages by GitHub Actions"
        exclude_assets: ./npc
