name: NPC Workflow

on:
  pull_request:
    branches: [main]
    paths:
      - 'npc/**'
      - '!npc/conversations.json'
  push:
    branches: [main]
    paths:
      - 'npc/conversations.json'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Validate changes
        run: |
          cd npc
          python ../src/validate.py

  convert:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Convert Markdown files to JSON
        run: |
          cd npc
          python ../src/md_to_json.py
  
      - name: Commit conversations.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update conversations.json"
          file_pattern: npc/conversations.json
          branch: ${{ github.head_ref }}

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'
        path: 'main'

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'gh-pages'

    - name: Copy updated docs to gh-pages branch
      run: |
        cp -r main/npc/api/* gh-pages/npc/api
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './npc/api'
        publish_branch: gh-pages
        allow_empty_commit: true
        keep_files: true
        commit_message: "Deployed to GitHub Pages by GitHub Actions"
        exclude_assets: ./docs
        
