name: Deploy static content to Pages

on:
  push:
    paths:
      - 'tibia/npc/**'
      - 'tibia/docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - '.'
          - 'npc'
          - 'docs'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        if: ${{ startsWith(github.event.path, 'tibia/npc/') }}
        uses: actions/upload-artifact@v2
        with:
          name: npc
          path: 'npc'
      - name: Upload artifact
        if: ${{ startsWith(github.event.path, 'tibia/docs/') }}
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: 'docs'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          path: ${{ matrix.directory }}
          base-dir: ${{ if startsWith(github.event.path, 'tibia/npc/'), 'npc', if startsWith(github.event.path, 'tibia/docs/'), 'docs', '' }}
