name: Validate NPC changes

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'tibia/npc/**'
      - '!tibia/npc/conversations.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Validate changes
      run: |
        cd tibia/npc
        python ../src/validate.py
